import {test,expect,type Page} from '@playwright/test'
const KEY='return-path.sample.v1'
async function open(page:Page){await page.goto('./');await expect(page.getByRole('heading',{name:'Prepare a return invitation'})).toBeVisible()}
async function preview(page:Page){await page.getByRole('button',{name:'Preview local timeline'}).click();await expect(page.getByRole('dialog')).toBeVisible()}
async function run(page:Page){await preview(page);await page.getByRole('button',{name:'Confirm local simulation'}).click();await expect(page.getByRole('heading',{name:'A quiet timeline'})).toBeVisible()}
async function policy(page:Page,gap='72',max='1'){await page.getByRole('button',{name:/03 Care policy/}).click();await page.getByLabel('Minimum spacing').selectOption(gap);await page.getByLabel('Rolling seven-day ceiling').selectOption(max);await page.getByRole('button',{name:'Review policy revision'}).click();await page.getByRole('button',{name:'Accept policy revision'}).click()}
async function reset(page:Page){await page.getByRole('button',{name:'Review sample reset'}).click();await page.getByRole('button',{name:'Confirm sample reset'}).click()}
test.beforeEach(async({page})=>{const errors:string[]=[];const requests:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4192/'))requests.push(r.url())});await page.addInitScript(()=>{if(!sessionStorage.getItem('return-path-test-seeded')){localStorage.clear();sessionStorage.setItem('return-path-test-seeded','yes')}});(page as Page & {checks:()=>void}).checks=()=>{expect(errors).toEqual([]);expect(requests).toEqual([])}})
test.afterEach(async({page})=>{(page as Page & {checks:()=>void}).checks()})
test('primary value destination preview and exact timeline',async({page})=>{await open(page);await expect(page.getByText('Your three saved stops are ready.',{exact:false})).toBeVisible();await page.getByRole('button',{name:/Return destination/}).click();await expect(page.getByRole('dialog')).toContainText('/workspace/walking-plan/final-stop');await page.getByRole('button',{name:'Back to invitation'}).click();await preview(page);await expect(page.getByRole('dialog')).toContainText('2 eligible, 4 suppressed');await expect(page.getByRole('dialog').locator('li')).toHaveCount(6);await page.getByRole('button',{name:'Confirm local simulation'}).click();const first=page.locator('.run-card').first();await expect(first.locator('.badge.eligible')).toHaveCount(2);await expect(first).toContainText('72-hour spacing');await expect(first).toContainText('no consent');await expect(page.getByRole('heading',{name:'A quiet timeline'})).toBeFocused()})
test('preview cancel and Escape do not save',async({page})=>{await open(page);await preview(page);await page.getByRole('button',{name:'Cancel preview'}).click();expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBeNull();await preview(page);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Preview local timeline'})).toBeFocused();expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBeNull()})
test('repeated run cannot revive accepted attempts',async({page})=>{await open(page);await run(page);await page.getByRole('button',{name:/Prepare another invitation/}).click();await run(page);const newest=page.locator('.run-card').first();await expect(newest.locator('.badge.eligible')).toHaveCount(0);await expect(newest).toContainText('already reviewed');await expect(page.locator('.run-card').last().locator('.badge.eligible')).toHaveCount(2)})
test('C03 optout and goal completion suppress all channels',async({page})=>{await open(page);await page.getByLabel('Start with a dormant cohort').selectOption('C03');await expect(page.getByText('Opted out',{exact:true})).toBeVisible();for(const channel of ['email','push','in-app']){await page.getByLabel('Invitation channel').selectOption(channel);await preview(page);const d=page.getByRole('dialog');await expect(d).toContainText('0 eligible, 6 suppressed');await expect(d).toContainText('opted out');await expect(d).toContainText('goal is already complete');await page.keyboard.press('Escape')}})
test('Clover consent does not override preference',async({page})=>{await open(page);await page.getByLabel('Start with a dormant cohort').selectOption('C02');await preview(page);await expect(page.getByRole('dialog')).toContainText('prefers in-app');await expect(page.getByRole('dialog')).toContainText('72-hour spacing');await page.keyboard.press('Escape');await page.getByLabel('Invitation channel').selectOption('in-app');await run(page);await expect(page.locator('.run-card .badge.eligible')).toHaveCount(2);await expect(page.locator('.run-card')).toContainText('no consent')})
test('Birch quiet hours differ by local date',async({page})=>{await open(page);await page.getByLabel('Invitation channel').selectOption('push');await page.getByRole('button',{name:/Birch P02/}).click();await expect(page.getByText('2026-10-04 01:00 UTC+09:00',{exact:true})).toBeVisible();await preview(page);await expect(page.getByRole('dialog')).toContainText('0 eligible, 6 suppressed');await expect(page.getByRole('dialog')).toContainText('local quiet hours');await page.keyboard.press('Escape');await page.getByLabel('Timeline starts').selectOption('2026-10-04T05:00:00.000Z');await run(page);await expect(page.locator('.run-card .badge.eligible')).toHaveCount(2)})
test('exact72h gap allows Fern at day1 and144h at day7',async({page})=>{await open(page);await page.getByLabel('Start with a dormant cohort').selectOption('C02');await run(page);const rows=page.locator('.run-card li').filter({hasText:'Fern P04'});await expect(rows).toHaveCount(3);await expect(rows.nth(0)).toContainText('Suppressed');await expect(rows.nth(1)).toContainText('Eligible');await expect(rows.nth(2)).toContainText('Eligible')})
test('rolling week seed and exact lower boundary',async({page})=>{await open(page);await policy(page);await page.getByRole('button',{name:'01 Return invitation'}).click();await run(page);const rows=page.locator('.run-card li').filter({hasText:'Aster P01'});await expect(rows.nth(0)).toContainText('1 invitations in a rolling');await expect(rows.nth(1)).toContainText('1 invitations in a rolling');await expect(rows.nth(2)).toContainText('Eligible')})
test('one-per-week with no seed allows exact7d boundary',async({page})=>{await open(page);await policy(page);await page.getByRole('button',{name:'01 Return invitation'}).click();await page.getByLabel('Start with a dormant cohort').selectOption('C02');await page.getByLabel('Invitation channel').selectOption('in-app');await run(page);const rows=page.locator('.run-card li').filter({hasText:'Clover P03'});await expect(rows.nth(0)).toContainText('Eligible');await expect(rows.nth(1)).toContainText('Suppressed');await expect(rows.nth(2)).toContainText('Eligible')})
test('policy preview cancel does not change accepted version',async({page})=>{await open(page);await page.getByRole('button',{name:/03 Care policy/}).click();await page.getByLabel('Minimum spacing').selectOption('168');await page.getByRole('button',{name:'Review policy revision'}).click();await page.keyboard.press('Escape');await expect(page.getByText('Accepted policy v1',{exact:true})).toBeVisible();expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBeNull()})
test('accepted policy revision preserves history and earlier frequency limits',async({page})=>{await open(page);await policy(page,'168','1');await page.getByRole('button',{name:'01 Return invitation'}).click();await run(page);const old=await page.locator('.run-card').innerText();await policy(page,'24','3');await page.getByRole('button',{name:/02 Local timeline/}).click();expect(await page.locator('.run-card').innerText()).toBe(old);await page.getByRole('button',{name:/Prepare another invitation/}).click();await page.getByLabel('Timeline starts').selectOption('2026-10-04T05:00:00.000Z');await run(page);await expect(page.locator('.run-card').first().locator('.badge.eligible')).toHaveCount(0);await expect(page.locator('.run-card').last()).toContainText('Policy v2');await expect(page.locator('.run-card').first()).toContainText('Policy v3')})
test('overlapping out-of-order run protects future accepted invitations',async({page})=>{await open(page);await page.getByLabel('Timeline starts').selectOption('2026-10-10T16:00:00.000Z');await run(page);await page.getByRole('button',{name:/Prepare another invitation/}).click();await page.getByLabel('Timeline starts').selectOption('2026-10-03T16:00:00.000Z');await run(page);const rows=page.locator('.run-card').first().locator('li').filter({hasText:'Aster P01'});await expect(rows.nth(0)).toContainText('Eligible');await expect(rows.nth(1)).toContainText('Suppressed');await expect(rows.nth(2)).toContainText('already reviewed')})
test('same start/end quiet hours cannot be accepted',async({page})=>{await open(page);await page.getByRole('button',{name:/03 Care policy/}).click();await page.getByLabel('Quiet hours end').selectOption('21');await expect(page.getByRole('alert')).toContainText('different start');await expect(page.getByRole('button',{name:'Review policy revision'})).toBeDisabled()})
test('compatible refresh retains timeline and policies',async({page})=>{await open(page);await run(page);await page.reload();await expect(page.getByRole('status')).toContainText('Compatible sample restored');await page.getByRole('button',{name:/02 Local timeline/}).click();await expect(page.locator('.run-card')).toHaveCount(1);await expect(page.locator('.run-card .badge.eligible')).toHaveCount(2)})
test('corrupt saved data is preserved through reset cancellation',async({page})=>{await page.addInitScript(k=>localStorage.setItem(k,'broken bytes'),KEY);await open(page);await expect(page.getByRole('status')).toContainText('incompatible');await expect(page.getByRole('button',{name:'Preview local timeline'})).toBeDisabled();await page.getByRole('button',{name:'Review sample reset'}).click();await page.keyboard.press('Escape');expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBe('broken bytes');await reset(page);await expect(page.getByRole('button',{name:'Preview local timeline'})).toBeEnabled();await expect(page.getByRole('button',{name:'Undo sample reset'})).toHaveCount(0);await run(page)})
test('tampered run outcome and unknown reference are incompatible',async({page})=>{await open(page);await run(page);const raw=await page.evaluate(k=>localStorage.getItem(k)!,KEY);const saved=JSON.parse(raw);saved.runs[0].outcomes[0].profile='P99';await page.addInitScript(({key,raw})=>localStorage.setItem(key,raw),{key:KEY,raw:JSON.stringify(saved)});await page.reload();await expect(page.getByRole('status')).toContainText('incompatible');await expect(page.getByRole('button',{name:'Preview local timeline'})).toBeDisabled()})
test('same-revision raw-byte change expires simulation review',async({page})=>{await open(page);await page.evaluate(k=>localStorage.setItem(k,'{"schema":1,"revision":0,"policies":[{"version":1,"policy":{"gapHours":72,"maxWeek":2,"quietStart":21,"quietEnd":8}}],"runs":[]}'),KEY);await preview(page);await page.evaluate(k=>localStorage.setItem(k,localStorage.getItem(k)!+' '),KEY);await page.getByRole('button',{name:'Confirm local simulation'}).click();await expect(page.getByRole('alert')).toContainText('Preview expired');expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).runs.length,KEY)).toBe(0)})
test('reset rejects changed corrupt bytes and then accepts fresh review',async({page})=>{await page.addInitScript(k=>localStorage.setItem(k,'first corruption'),KEY);await open(page);await page.getByRole('button',{name:'Review sample reset'}).click();await page.evaluate(k=>localStorage.setItem(k,'different corruption'),KEY);await page.getByRole('button',{name:'Confirm sample reset'}).click();await expect(page.getByRole('alert')).toContainText('Preview expired');expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBe('different corruption');await reset(page);await run(page)})
test('reset Undo restores exact previous history and expires after next action',async({page})=>{await open(page);await run(page);const before=await page.evaluate(k=>localStorage.getItem(k),KEY);await reset(page);await page.getByRole('button',{name:'Undo sample reset'}).click();expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBe(before);await reset(page);await run(page);await expect(page.getByRole('button',{name:'Undo sample reset'})).toHaveCount(0)})
test('reset Undo cannot overwrite another saved change',async({page})=>{await open(page);await run(page);await reset(page);await page.evaluate(k=>localStorage.setItem(k,'another tab'),KEY);await page.getByRole('button',{name:'Undo sample reset'}).click();await expect(page.getByRole('alert')).toContainText('Undo expired');expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBe('another tab')})
test('read failure with working write never overwrites unseen bytes',async({page})=>{await page.addInitScript(k=>{const get=Storage.prototype.getItem,set=Storage.prototype.setItem;set.call(localStorage,k,'unseen bytes');let writes=0;Object.defineProperty(window,'returnPathStorageCheck',{value:()=>({writes,raw:get.call(localStorage,k)})});Storage.prototype.getItem=function(key){if(key===k)throw Error('read unavailable');return get.call(this,key)};Storage.prototype.setItem=function(key,value){if(key===k)writes++;set.call(this,key,value)}},KEY);await open(page);await expect(page.getByRole('status')).toContainText('unseen bytes');await run(page);await expect(page.getByRole('status')).toContainText('Kept in memory');await reset(page);await expect(page.getByRole('status')).toContainText('unseen bytes');await expect(page.getByRole('button',{name:'Undo sample reset'})).toHaveCount(0);expect(await page.evaluate(()=>(window as unknown as {returnPathStorageCheck:()=>unknown}).returnPathStorageCheck())).toEqual({writes:0,raw:'unseen bytes'})})
test('storage getter failure keeps a useful in-memory timeline',async({page})=>{await page.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('getter unavailable')}}));await open(page);await run(page);await expect(page.locator('.run-card')).toHaveCount(1);await expect(page.getByRole('status')).toContainText('Kept in memory')})
test('write failure keeps memory with explicit refresh warning',async({page})=>{await page.addInitScript(k=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key===k)throw Error('quota');set.call(this,key,value)}},KEY);await open(page);await run(page);await expect(page.getByRole('status')).toContainText('refresh may lose this change');expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBeNull()})
test('changed draft selection expires preview',async({page})=>{await open(page);await preview(page);await page.locator('#channel').selectOption('push',{force:true});await page.getByRole('button',{name:'Confirm local simulation'}).click();await expect(page.getByRole('alert')).toContainText('selection, draft or saved data changed');expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBeNull()})
test('keyboard forward and reverse tab stay inside modal and Escape returns focus',async({page})=>{await open(page);await page.getByRole('button',{name:'Preview local timeline'}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toBeVisible();for(let i=0;i<12;i++){await page.keyboard.press('Tab');expect(await page.evaluate(()=>!!document.activeElement?.closest('dialog'))).toBe(true)}for(let i=0;i<12;i++){await page.keyboard.press('Shift+Tab');expect(await page.evaluate(()=>!!document.activeElement?.closest('dialog'))).toBe(true)}await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Preview local timeline'})).toBeFocused()})
test('all invitation controls fit1280x633 for every cohort and profile',async({page})=>{await open(page);for(const cohort of ['C01','C02','C03']){await page.getByLabel('Start with a dormant cohort').selectOption(cohort);const buttons=page.locator('.profile');for(let i=0;i<2;i++){await buttons.nth(i).click();for(const sel of ['#cohort','#channel','#start','.invitation>.primary']){const box=await page.locator(sel).boundingBox();expect(box!.y).toBeGreaterThanOrEqual(0);expect(box!.y+box!.height).toBeLessThanOrEqual(633)}}}})
for(const width of [320,390])test(`narrow${width} invitation policy timeline and dialogs have no horizontal overflow`,async({page})=>{await page.setViewportSize({width,height:844});await open(page);const check=async()=>expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await check();await page.getByRole('button',{name:/Return destination/}).click();await check();await page.keyboard.press('Escape');await run(page);await check();await page.getByRole('button',{name:/03 Care policy/}).click();await check();await page.getByLabel('Minimum spacing').selectOption('168');await page.getByRole('button',{name:'Review policy revision'}).click();await check();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Review sample reset'}).click();await check();await page.keyboard.press('Escape')})
test('all product reviewer links and security metadata exist in build',async({page,request})=>{await open(page);for(const link of ['Product case','Try the sample','Evidence & limits']){const href=await page.getByRole('link',{name:link}).getAttribute('href');const res=await request.get(href!);expect(res.status()).toBe(200);expect((await res.text()).length).toBeGreaterThan(100)}await expect(page.locator('meta[http-equiv="Content-Security-Policy"]')).toHaveAttribute('content',/connect-src 'none'/);await expect(page.locator('meta[name="referrer"]')).toHaveAttribute('content','no-referrer')})

test('reviewed reset clears audience channel and time selections',async({page})=>{await open(page);await page.getByLabel('Start with a dormant cohort').selectOption('C03');await page.getByLabel('Invitation channel').selectOption('push');await page.getByLabel('Timeline starts').selectOption('2026-10-10T16:00:00.000Z');await reset(page);await expect(page.getByLabel('Start with a dormant cohort')).toHaveValue('C01');await expect(page.getByLabel('Invitation channel')).toHaveValue('email');await expect(page.getByLabel('Timeline starts')).toHaveValue('2026-10-03T16:00:00.000Z');await expect(page.getByRole('button',{name:/Aster P01/})).toHaveAttribute('aria-pressed','true')})

test('storage read recovery reset discloses replacement of reviewed bytes without Undo',async({page})=>{await page.addInitScript(k=>{const get=Storage.prototype.getItem,set=Storage.prototype.setItem;set.call(localStorage,k,'previously unseen history');let readable=false;Object.defineProperty(window,'restoreReturnPathRead',{value:()=>{readable=true}});Storage.prototype.getItem=function(key){if(key===k&&!readable)throw Error('temporary read failure');return get.call(this,key)}},KEY);await open(page);await run(page);await page.evaluate(()=>(window as unknown as {restoreReturnPathRead:()=>void}).restoreReturnPathRead());await page.getByRole('button',{name:'Review sample reset'}).click();await expect(page.getByRole('dialog')).toContainText('Storage can now be read');await expect(page.getByRole('dialog')).toContainText('replaces the now-reviewed saved sample');await expect(page.getByRole('dialog')).toContainText('cannot be restored with Undo');await page.keyboard.press('Escape');expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBe('previously unseen history');await reset(page);expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).runs.length,KEY)).toBe(0);await expect(page.getByRole('button',{name:'Undo sample reset'})).toHaveCount(0)})
test('run history cap is explained before a new review and reset recovers',async({page})=>{await open(page);for(let i=0;i<30;i++){if(i)await page.getByRole('button',{name:/Prepare another invitation/}).click();await run(page)}await page.getByRole('button',{name:/Prepare another invitation/}).click();await page.getByRole('button',{name:'Preview local timeline'}).click();await expect(page.getByRole('alert')).toContainText('30 runs');await expect(page.getByRole('dialog')).toHaveCount(0);await reset(page);await run(page);await expect(page.locator('.run-card')).toHaveCount(1)})
test('policy history cap is explained before review and reset recovers',async({page})=>{await open(page);for(let i=0;i<29;i++)await policy(page,'72',i%2?'2':'1');await page.getByLabel('Rolling seven-day ceiling').selectOption('3');await page.getByRole('button',{name:'Review policy revision'}).click();await expect(page.getByRole('alert')).toContainText('30 versions');await expect(page.getByRole('dialog')).toHaveCount(0);await reset(page);await page.getByRole('button',{name:/03 Care policy/}).click();await expect(page.getByText('Accepted policy v1',{exact:true})).toBeVisible()})
