import {useRef,useState} from 'react'
import {cohorts,CLOCK,profiles,getProfile,localTime,message,starts,type Channel} from './fixtures'
import {latest,simulate,validPolicy,type Outcome,type Policy,type Run,type Scope} from './domain'
import {SampleStore,type Review,type Action} from './storage'
import Dialog from './Dialog'
const channelLabel=(c:Channel)=>c==='in-app'?'In-app':c==='email'?'Email':'Push'
const hh=(h:number)=>String(h).padStart(2,'0')+':00'
function Outcomes({rows}:{rows:Outcome[]}){return <ol className="outcomes">{rows.map(o=>{const p=getProfile(o.profile);return <li key={o.profile+o.time}><div className="time"><span>{o.time.slice(5,10)}</span><strong>{o.time.slice(11,16)} UTC</strong></div><div className="outcome-content"><div className="outcome-top"><strong>{p.name} <small>{p.id}</small></strong><span className={o.eligible?'badge eligible':'badge'}>{o.eligible?'Eligible':'Suppressed'}</span></div><p>{o.reason.split(' · ')[1]}</p><small>{localTime(o.time,p)} · {channelLabel(o.channel)}</small><details><summary>Value & return destination</summary><p>{message(p)}</p><p><strong>{p.destination}</strong></p><code>{p.path}</code></details></div></li>})}</ol>}
function RunCard({run}:{run:Run}){return <article className="run-card"><div className="run-head"><div><span className="eyebrow">Accepted local snapshot</span><h3>Run {run.id} · {cohorts.find(c=>c.id===run.scope.cohort)?.name}</h3></div><span className="badge">Policy v{run.policyVersion}</span></div><p className="run-description">{channelLabel(run.scope.channel)} · starts {run.scope.start.slice(0,16).replace('T',' ')} UTC · {run.policy.gapHours}h minimum gap · {run.policy.maxWeek}/7 days · quiet {hh(run.policy.quietStart)}–{hh(run.policy.quietEnd)} local</p><Outcomes rows={run.outcomes}/></article>}
export default function App(){
 const [store]=useState(()=>new SampleStore(()=>window.localStorage));const [state,setState]=useState(store.state)
 const [scope,setScope]=useState<Scope>({cohort:'C01',channel:'email',start:CLOCK});const [profileId,setProfileId]=useState('P01')
 const [tab,setTab]=useState<'invitation'|'timeline'|'policy'>('invitation');const [draft,setDraft]=useState<Policy>({...latest(state).policy})
 const [review,setReview]=useState<Review|null>(null);const [destination,setDestination]=useState(false);const [notice,setNotice]=useState(store.notice);const [error,setError]=useState('')
 const heading=useRef<HTMLHeadingElement>(null);const p=getProfile(profileId);const policy=latest(state)
 const rows=review?.action.kind==='run'?simulate(state,review.action.scope):[]
 function update(){setState({...store.state});setNotice(store.notice)}
 function open(action:Action){try{const r=store.preview(action);update();setError('');setReview(r)}catch(e){update();setError((e as Error).message)}}
 function cancel(){setReview(null);setError('');setNotice('Preview cancelled. No local changes were made. '+store.notice)}
 function confirm(){if(!review)return;const current:Action=review.action.kind==='run'?{kind:'run',scope}:review.action.kind==='policy'?{kind:'policy',policy:draft}:{kind:'reset'};try{store.confirm(review,current);update();setReview(null);setError('');if(current.kind==='run'){setTab('timeline');setNotice(`Run ${store.state.runs.length} added. ${rows.filter(o=>o.eligible).length} eligible; ${rows.filter(o=>!o.eligible).length} suppressed. ${store.notice}`)}if(current.kind==='reset'){setScope({cohort:'C01',channel:'email',start:CLOCK});setProfileId('P01');setDraft({...latest(store.state).policy});setTab('invitation');setNotice('Sample reset. '+store.notice)}if(current.kind==='policy')setNotice(`Policy v${latest(store.state).version} accepted. Past runs retain their original policy. ${store.notice}`);requestAnimationFrame(()=>heading.current?.focus())}catch(e){update();setReview(null);setError((e as Error).message)}}
 function undo(){try{store.undoReset();update();setDraft({...latest(store.state).policy});setError('');setNotice('Previous timeline and policies restored. '+store.notice)}catch(e){update();setError((e as Error).message)}}
 function chooseCohort(id:string){setScope({...scope,cohort:id});setProfileId(profiles.find(p=>p.cohort===id)!.id)}
 return <><a className="skip" href="#main">Skip to workspace</a><header><a className="brand" href="./" aria-label="Return Path home"><span className="brand-mark">↗</span> Return Path</a><span className="fiction">Northstar · fictional local prototype</span></header>
 <section className="intro"><div><span className="eyebrow">A reason to return</span><h1>Pick up something<br/><em>that still matters.</em></h1></div><p>A return invitation should offer a useful next step and respect someone’s time. Explore who has a reason to return, and who deserves room.</p></section>
 <nav className="workspace-nav" aria-label="Workspace"><button aria-current={tab==='invitation'?'page':undefined} onClick={()=>setTab('invitation')}><span>01</span> Return invitation</button><button aria-current={tab==='timeline'?'page':undefined} onClick={()=>setTab('timeline')}><span>02</span> Local timeline {state.runs.length>0&&<small>{state.runs.length}</small>}</button><button aria-current={tab==='policy'?'page':undefined} onClick={()=>{setDraft({...policy.policy});setTab('policy')}}><span>03</span> Care policy <small>v{policy.version}</small></button></nav>
 <main id="main"><div className="status" role="status" aria-live="polite">{notice}</div>{error&&<div role="alert" className="error">{error}</div>}
 {tab==='invitation'&&<><div className="section-heading"><h2 ref={heading} tabIndex={-1}>Prepare a return invitation</h2><span>Sample clock · Oct 3, 2026 · 16:00 UTC</span></div><div className="workspace"><section className="audience"><label htmlFor="cohort">Start with a dormant cohort</label><select id="cohort" value={scope.cohort} onChange={e=>chooseCohort(e.target.value)}>{cohorts.map(c=><option key={c.id} value={c.id}>{c.id} · {c.name}</option>)}</select><p className="muted cohort-detail">{cohorts.find(c=>c.id===scope.cohort)?.detail} Two fictional profiles per cohort.</p><div className="profiles">{profiles.filter(p=>p.cohort===scope.cohort).map(item=><button className={item.id===profileId?'profile selected':'profile'} key={item.id} aria-pressed={item.id===profileId} onClick={()=>setProfileId(item.id)}><span className="avatar">{item.name[0]}</span><div><strong>{item.name} <small>{item.id}</small></strong><span>{item.reason}</span></div><span className="arrow">↗</span></button>)}</div><div className="profile-facts"><span className="eyebrow">{p.name}’s context</span><h3>{p.goal}</h3><dl><div><dt>Prefers</dt><dd>{channelLabel(p.preferred)}</dd></div><div><dt>Consent</dt><dd>{p.optedOut?'Opted out':p.consent.map(channelLabel).join(', ')}</dd></div><div><dt>Local time</dt><dd>{localTime(scope.start,p)}</dd></div><div><dt>Last invitation</dt><dd>{p.lastTouch?p.lastTouch.slice(0,16).replace('T',' ')+' UTC':'None in sample'}</dd></div><div><dt>Eligibility</dt><dd>{p.eligible?'Unfinished goal':'Goal complete'}</dd></div></dl></div></section>
 <section className="invitation"><div className="preview-title"><span className="eyebrow">Value before volume</span><span className="badge">Preview only</span></div><h3>A small next step,<br/> {p.name}.</h3><p className="message">{p.value}</p><p className="permission">Return when it works for you.</p><button className="destination" onClick={()=>setDestination(true)}><span>Return destination<strong>{p.destination}</strong></span><span>↗</span></button><div className="simulation-form"><div><label htmlFor="channel">Invitation channel</label><select id="channel" value={scope.channel} onChange={e=>setScope({...scope,channel:e.target.value as Channel})}><option value="email">Email</option><option value="push">Push</option><option value="in-app">In-app</option></select></div><div><label htmlFor="start">Timeline starts</label><select id="start" value={scope.start} onChange={e=>setScope({...scope,start:e.target.value})}>{starts.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></div></div><button className="primary" onClick={()=>open({kind:'run',scope})} disabled={store.blocked}>Preview local timeline <span>→</span></button><p className="policy-note">Policy v{policy.version}: {policy.policy.gapHours}h spacing · at most {policy.policy.maxWeek} in 7 days · quiet {hh(policy.policy.quietStart)}–{hh(policy.policy.quietEnd)} local. All channels obey the same limits.</p><p className="tiny">Both cohort profiles · start, +24 hours, +7 days. Nothing is sent.</p></section></div></>}
 {tab==='timeline'&&<><div className="section-heading"><h2 ref={heading} tabIndex={-1}>A quiet timeline</h2><button className="text-button" onClick={()=>setTab('invitation')}>Prepare another invitation ↗</button></div><p className="explain">Every outcome explains the value or the protection behind the decision. Accepted snapshots keep their original scope and policy. Repeating a reviewed attempt cannot make it eligible.</p>{state.runs.length===0?<div className="empty"><span>↗</span><h3>No invitations simulated yet.</h3><p>Choose a cohort and preview the local timeline first.</p><button className="primary" onClick={()=>setTab('invitation')}>Prepare invitation</button></div>:[...state.runs].reverse().map(r=><RunCard key={r.id} run={r}/>)}</>}
 {tab==='policy'&&<><div className="section-heading"><h2 ref={heading} tabIndex={-1}>Make room for life outside the product</h2><span>Accepted policy v{policy.version}</span></div><div className="policy-grid"><section className="policy-panel"><span className="eyebrow">Draft a care policy</span><p>Consent, opt-out and unfinished value are required. Preferences are honored even when another channel has permission.</p><div className="policy-fields"><div><label htmlFor="gap">Minimum spacing</label><select id="gap" value={draft.gapHours} onChange={e=>setDraft({...draft,gapHours:Number(e.target.value)})}><option value={24}>24 hours</option><option value={72}>72 hours</option><option value={168}>168 hours</option></select></div><div><label htmlFor="max">Rolling seven-day ceiling</label><select id="max" value={draft.maxWeek} onChange={e=>setDraft({...draft,maxWeek:Number(e.target.value)})}><option value={1}>1 invitation</option><option value={2}>2 invitations</option><option value={3}>3 invitations</option></select></div><div><label htmlFor="quiet-start">Quiet hours start (inclusive)</label><select id="quiet-start" value={draft.quietStart} onChange={e=>setDraft({...draft,quietStart:Number(e.target.value)})}>{Array.from({length:24},(_,h)=><option value={h} key={h}>{hh(h)}</option>)}</select></div><div><label htmlFor="quiet-end">Quiet hours end (exclusive)</label><select id="quiet-end" value={draft.quietEnd} onChange={e=>setDraft({...draft,quietEnd:Number(e.target.value)})}>{Array.from({length:24},(_,h)=><option value={h} key={h}>{hh(h)}</option>)}</select></div></div>{!validPolicy(draft)&&<p role="alert" className="error">Choose different start and end times for quiet hours.</p>}<button className="primary" disabled={!validPolicy(draft)||store.blocked||JSON.stringify(draft)===JSON.stringify(policy.policy)} onClick={()=>open({kind:'policy',policy:draft})}>Review policy revision →</button></section><aside className="policy-rationale"><span className="eyebrow">Why these guardrails?</span><h3>Attention is part of the experience.</h3><p>A useful saved goal does not give the product unlimited permission to interrupt.</p><ul><li>Quiet hours follow each fictional profile’s fixed local offset, including across midnight.</li><li>Exactly the minimum spacing is allowed. The rolling window excludes exactly seven days ago and includes the current instant.</li><li>Prior runs preserve their accepted spacing and ceiling. A relaxed revision cannot erase those protections; the strictest accepted run limits still apply.</li><li>All outcomes, including suppression, reserve that exact profile and time. A repeat stays suppressed.</li></ul><details><summary>Accepted policy history ({state.policies.length})</summary>{state.policies.map(v=><p key={v.version}>v{v.version} · {v.policy.gapHours}h · {v.policy.maxWeek}/7d · {hh(v.policy.quietStart)}–{hh(v.policy.quietEnd)}</p>)}</details></aside></div></>}
 <section className="recovery"><div><h3>Try a different scenario</h3><p>Review a reset to clear all runs and policy versions. Undo restores a compatible previous sample until the next accepted action or refresh.</p></div><div><button className="secondary" onClick={()=>open({kind:'reset'})}>Review sample reset</button>{store.canUndo&&<button className="text-button" onClick={undo}>Undo sample reset</button>}</div></section>
 </main><footer><span>Original fictional inputs. Local simulation. No delivery, tracking or accounts.</span><span>Product & program direction: Mo · AI-assisted implementation & verification</span><div><a href="docs/product/Case_Study.html">Product case</a><a href="docs/product/Sample_Walkthrough.html">Try the sample</a><a href="docs/product/Validation.html">Evidence & limits</a></div></footer>
 {review&&<Dialog title={review.action.kind==='run'?'Review this local timeline':review.action.kind==='policy'?'Review the care policy':'Review a fresh sample'} onCancel={cancel}>{review.action.kind==='run'?<><p>This adds six fictional outcomes for <strong>{cohorts.find(c=>c.id===scope.cohort)?.name}</strong> through {channelLabel(scope.channel)}, under policy v{policy.version}. <strong>{rows.filter(o=>o.eligible).length} eligible, {rows.filter(o=>!o.eligible).length} suppressed.</strong> Nothing is sent.</p><Outcomes rows={rows}/></>:review.action.kind==='policy'?<><p>Accept policy v{policy.version+1}: <strong>{draft.gapHours}h spacing, {draft.maxWeek} invitations per 7 days, quiet {hh(draft.quietStart)}–{hh(draft.quietEnd)} local.</strong></p><p>Previous runs and exact suppressed attempts remain unchanged. Earlier accepted run limits still protect attention when this draft is more permissive.</p></>:<><p>Clear <strong>{state.runs.length} runs and {state.policies.length} policy versions</strong>, and start the original fictional sample again.</p><p>{store.blocked?'This replaces the incompatible saved bytes you are reviewing. Corrupt saved data cannot be restored with Undo.':!review.reading.readable?'Storage is unreadable. The reset stays in memory and preserves unseen saved bytes; Undo is unavailable.':store.memoryOnly?'Storage can now be read. This reset replaces the now-reviewed saved sample with the original fictional sample. Previously unseen history cannot be restored with Undo.':'Undo can restore this compatible sample until the next accepted action or refresh. It does not restore another browser tab’s later changes.'}</p></>}<div className="dialog-actions"><button className="secondary" onClick={cancel}>Cancel preview</button><button className="primary" onClick={confirm}>{review.action.kind==='run'?'Confirm local simulation':review.action.kind==='policy'?'Accept policy revision':'Confirm sample reset'}</button></div></Dialog>}
 {destination&&<Dialog title={p.destination} onCancel={()=>setDestination(false)}><span className="badge">Local destination preview · {p.id}</span><p>{p.value}</p><div className="destination-preview"><span className="eyebrow">Your saved next step</span><h3>{p.goal}</h3><p>{p.reason}.</p><p>This invitation opens directly to <strong>{p.destination}</strong>. The saved context is carried forward so the learner does not have to start over.</p><code>{p.path}</code></div><p className="tiny">This is a destination preview; the rest of the fictional workspace is outside this prototype.</p><div className="dialog-actions"><button className="primary" onClick={()=>setDestination(false)}>Back to invitation</button></div></Dialog>}
 </>
}
