export type Channel = 'email' | 'push' | 'in-app'
export type Profile = {id:string; name:string; cohort:string; reason:string; goal:string; value:string; destination:string; path:string; offset:number; timezone:string; consent:Channel[]; preferred:Channel; optedOut:boolean; eligible:boolean; lastTouch:string|null}
export const CLOCK = '2026-10-03T16:00:00.000Z'
export const DAY = 86400000
export const cohorts = [{id:'C01',name:'A draft waiting',detail:'Paused after saving a useful first step.'},{id:'C02',name:'Time to reconsider',detail:'Busy schedules and changed priorities.'},{id:'C03',name:'Leave room',detail:'Finished goals and explicit preferences.'}] as const
export const profiles:Profile[] = [
{id:'P01',name:'Aster',cohort:'C01',reason:'Lost the next step after saving a draft',goal:'Finish a neighborhood walking plan',value:'Your three saved stops are ready. Pick the final stop in about five minutes.',destination:'Walking plan · choose the final stop',path:'/workspace/walking-plan/final-stop',offset:-420,timezone:'UTC−07:00',consent:['email','in-app'],preferred:'email',optedOut:false,eligible:true,lastTouch:'2026-09-30T16:00:00.000Z'},
{id:'P02',name:'Birch',cohort:'C01',reason:'The mobile draft felt difficult to resume',goal:'Complete a small balcony planting plan',value:'Your light and space notes are saved. Compare two suitable plants in about five minutes.',destination:'Planting plan · compare two plants',path:'/workspace/planting-plan/compare',offset:540,timezone:'UTC+09:00',consent:['push','in-app'],preferred:'push',optedOut:false,eligible:true,lastTouch:null},
{id:'P03',name:'Clover',cohort:'C02',reason:'A busy week interrupted a chosen lesson',goal:'Resume a sketching exercise',value:'Your last sketch is saved. Continue the shading exercise in about ten minutes.',destination:'Sketching · resume shading exercise',path:'/workspace/sketching/shading',offset:60,timezone:'UTC+01:00',consent:['email','in-app'],preferred:'in-app',optedOut:false,eligible:true,lastTouch:null},
{id:'P04',name:'Fern',cohort:'C02',reason:'A recent reminder arrived before free time',goal:'Finish a simple repair checklist',value:'Your repair checklist has one item left. Review the saved safety notes in about five minutes.',destination:'Repair checklist · last item',path:'/workspace/repair-checklist/last-item',offset:-420,timezone:'UTC−07:00',consent:['email'],preferred:'email',optedOut:false,eligible:true,lastTouch:'2026-10-01T16:00:00.000Z'},
{id:'P05',name:'Juniper',cohort:'C03',reason:'Asked to stop return invitations',goal:'A saved recipe collection',value:'Your recipe collection remains available whenever you choose to open it.',destination:'Recipe collection · saved recipes',path:'/workspace/recipes/saved',offset:-420,timezone:'UTC−07:00',consent:[],preferred:'in-app',optedOut:true,eligible:true,lastTouch:null},
{id:'P06',name:'Moss',cohort:'C03',reason:'Already completed the original goal',goal:'A finished home reading corner',value:'Your completed reading-corner plan is available as a reference.',destination:'Reading corner · completed plan',path:'/workspace/reading-corner/completed',offset:60,timezone:'UTC+01:00',consent:['email','push','in-app'],preferred:'email',optedOut:false,eligible:false,lastTouch:null},
]
export const starts = [{id:CLOCK,label:'Oct 3 · 16:00 UTC (sample now)'},{id:'2026-10-04T05:00:00.000Z',label:'Oct 4 · 05:00 UTC (quiet-hours example)'},{id:'2026-10-10T16:00:00.000Z',label:'Oct 10 · 16:00 UTC (one week later)'}]
export function getProfile(id:string):Profile {const p=profiles.find(p=>p.id===id);if(!p)throw new Error('Unknown fictional profile');return p}
export function localTime(time:string,p:Profile):string {return new Date(Date.parse(time)+p.offset*60000).toISOString().replace('T',' ').slice(0,16)+' '+p.timezone}
export function message(p:Profile):string {return `A small next step, ${p.name}. ${p.value} Return when it works for you.`}
