import {describe,it,expect} from 'vitest'
import {SampleStore,type Store,type Action} from './storage'
import {addRun,DEFAULT_POLICY,initial} from './domain'
import {CLOCK} from './fixtures'
const run:Action={kind:'run',scope:{cohort:'C01',channel:'email',start:CLOCK}},reset:Action={kind:'reset'}
function fake(raw:string|null=null){let value=raw;const store:Store={getItem:()=>value,setItem:(_k,v)=>{value=v}};return {store,raw:()=>value,change:(v:string|null)=>{value=v}}}
describe('review binding and storage recovery',()=>{
 it('cancelled preview does not save or mutate',()=>{const f=fake(),s=new SampleStore(()=>f.store);s.preview(run);expect(f.raw()).toBe(null);expect(s.state.runs).toHaveLength(0)})
 it('confirm and compatible refresh retain immutable history',()=>{const f=fake(),s=new SampleStore(()=>f.store);s.confirm(s.preview(run),run);expect(new SampleStore(()=>f.store).state).toEqual(s.state)})
 it('rejects changed cohort, channel and time after preview',()=>{for(const change of [{cohort:'C02'},{channel:'push'},{start:'2026-10-10T16:00:00.000Z'}]){const f=fake(),s=new SampleStore(()=>f.store),p=s.preview(run);expect(()=>s.confirm(p,{kind:'run',scope:{...run.scope,...change}} as Action)).toThrow('expired');expect(f.raw()).toBe(null)}})
 it('rejects changed policy draft after preview',()=>{const f=fake(),s=new SampleStore(()=>f.store),a:Action={kind:'policy',policy:{...DEFAULT_POLICY,maxWeek:1}};expect(()=>s.confirm(s.preview(a),{kind:'policy',policy:{...DEFAULT_POLICY,gapHours:168}})).toThrow('expired')})
 it('changed raw bytes at identical revision reject confirmation',()=>{const f=fake(JSON.stringify(initial())),s=new SampleStore(()=>f.store),p=s.preview(run);f.change(JSON.stringify(initial(),null,2));expect(()=>s.confirm(p,run)).toThrow('expired');expect(s.state.runs).toHaveLength(0)})
 it('changed compatible data synchronizes and requires fresh review',()=>{const f=fake(),s=new SampleStore(()=>f.store),p=s.preview(run);f.change(JSON.stringify(addRun(initial(),run.scope)));expect(()=>s.confirm(p,run)).toThrow('expired');expect(s.state.runs).toHaveLength(1)})
 it('corrupt data stays unchanged until confirmed fresh reset',()=>{const f=fake('corrupt'),s=new SampleStore(()=>f.store);expect(()=>s.preview(run)).toThrow('incompatible');s.preview(reset);expect(f.raw()).toBe('corrupt');s.confirm(s.preview(reset),reset);expect(s.state).toEqual(initial());expect(s.canUndo).toBe(false)})
 it('reset raw-byte mismatch rejects and preserves new corruption',()=>{const f=fake('old'),s=new SampleStore(()=>f.store),p=s.preview(reset);f.change('new');expect(()=>s.confirm(p,reset)).toThrow('expired');expect(f.raw()).toBe('new')})
 it('unreadable get with successful set never writes unseen data',()=>{let writes=0;const s=new SampleStore(()=>({getItem:()=>{throw Error('blocked')},setItem:()=>{writes++}}));s.confirm(s.preview(run),run);s.confirm(s.preview(reset),reset);expect(writes).toBe(0);expect(s.notice).toContain('unseen bytes')})
 it('storage getter failure also stays in memory',()=>{const s=new SampleStore(()=>{throw Error('getter')});s.confirm(s.preview(run),run);expect(s.state.runs).toHaveLength(1);expect(s.memoryOnly).toBe(true)})
 it('write failure retains memory and allows safe retry',()=>{const f=fake();let fail=true;const s=new SampleStore(()=>({...f.store,setItem:(k,v)=>{if(fail)throw Error('quota');f.store.setItem(k,v)}}));s.confirm(s.preview(run),run);expect(s.notice).toContain('Saving is unavailable');expect(f.raw()).toBe(null);fail=false;s.confirm(s.preview(run),run);expect(new SampleStore(()=>f.store).state.runs).toHaveLength(2)})
 it('readability change expires reset, fresh readable reset is explicit',()=>{let readable=false,writes=0;const s=new SampleStore(()=>({getItem:()=>{if(!readable)throw Error('read');return 'unseen'},setItem:()=>{writes++}}));const p=s.preview(reset);readable=true;expect(()=>s.confirm(p,reset)).toThrow('expired');expect(writes).toBe(0);s.confirm(s.preview(reset),reset);expect(writes).toBe(1)})
 it('reset Undo restores prior history once, next action expires it',()=>{const f=fake(),s=new SampleStore(()=>f.store);s.confirm(s.preview(run),run);const old=structuredClone(s.state);s.confirm(s.preview(reset),reset);expect(s.canUndo).toBe(true);s.undoReset();expect(s.state).toEqual(old);expect(()=>s.undoReset()).toThrow();s.confirm(s.preview(reset),reset);s.confirm(s.preview(run),run);expect(s.canUndo).toBe(false)})
 it('reset Undo expires if raw bytes change',()=>{const f=fake(),s=new SampleStore(()=>f.store);s.confirm(s.preview(run),run);s.confirm(s.preview(reset),reset);f.change('changed');expect(()=>s.undoReset()).toThrow('expired');expect(f.raw()).toBe('changed')})
})
